### ISSUE TITLE
takeLatest issue

### ISSUE THREAD

**Issue by smashercosmo** [yelouafi/redux-saga#429]
When I run this simple code
```javascript
function* fetchUser() {
  yield 1;
}

function* watchLastFetchUser() {
  yield* takeLatest('USER_REQUESTED', fetchUser);
}

export default function* root() {
  yield [
    fork(watchLastFetchUser)
  ];
}
```
I get
```
redux-saga error: uncaught
at root 
 at watchLastFetchUser 
 TypeError: Cannot read property 'done' of undefined
```

I'm using saga's done() method for server rendering. Simple sagas, that yield simple effects work fine.
Simple implementation of takeLatest (like in docs) also works.

**Comment by Baisang** [comment]
Can you show the code you use to start the saga middleware etc.? Might be more helpful

**Comment by smashercosmo** [comment]
createStore.js
```javascript
import {createStore, applyMiddleware, compose} from 'redux';
import createSagaMiddleware, {END} from 'redux-saga';
import reducer from './reducers';

export default function(state) {
  const sagaMiddleware = createSagaMiddleware();

  const middleware = [
    sagaMiddleware
  ];

  const storeEnhancers = applyMiddleware(...middleware);
  const store = createStore(reducer, state, storeEnhancers);
  store.runSaga = sagaMiddleware.run;
  store.close = () => store.dispatch(END);

  return store;
}
```
serverRender.js
```javascript
const matchRoute = (req, res, next, routes, location, store, history) => {
  match({history, routes, location}, (error, redirectLocation, renderProps) => {
    /** some serever rendering code */

   const saga = store.runSaga(rootSaga);
    fetchComponentData(store, renderProps, saga)
      .then(() => sendHtml(req, res, store, renderProps))
      .catch(next);
    store.close();
  });
};
```
fetchComponentData.js
```javascript
export default function fetchComponentData(store, renderProps, saga) {
  const promises = renderProps.components
    .filter(component => component && component.fetchData)
    .map(component => component.fetchData)
    .map(fetchData => fetchData(store, renderProps));
  return Promise.all([...promises, saga.done]);
```
something like this

**Comment by smashercosmo** [comment]
Ok, further research shows that if you don't wrap takeLatest-saga in fork, then it starts working. Could somebody explain why?

**Comment by yelouafi** [comment]
Can you post a test case or a runnable gist? I tried the above snippet but couldn't reproduce the issue

**Comment by smashercosmo** [comment]
@yelouafi ok, I'll publish repo with complete example

**Comment by northerneyes** [comment]
We found the issue. The reason was that we was using node 6 with native generator implementation. With simple `yield` everything works fine, but for `yield*` with takeLatest it is not. Our babelrc file https://gist.github.com/northerneyes/382aeafce1cc94ca7bb0cba4ca83a60a

**Comment by smashercosmo** [comment]
Ok, here is an [example repo](https://github.com/smashercosmo/redux-saga). To reproduce the issue, just remove babel-plugin-transform-regenerator from .babelrc in real-world example. And run it on node 6 (which has native support for generators).

**Comment by smashercosmo** [comment]
@yelouafi did you have a chance to look at the issue? (not pushing :))

**Comment by yelouafi** [comment]
Sorry not yet. I'll take a look asap

**Comment by jrvidal** [comment]
This is most likely a V8 bug. The offending line points to a `return` method of a generator object returning `undefined`, which should never happen.

```javascript
function *foo() {
    yield *bar();
}

function bar() {
    let it = {
        next() {
            return { done: false, value: 1 };
        },
        [Symbol.iterator]() {
            return it;
        }
    };
    return it;
}

var gen = foo();
console.log(gen.next());
console.log(gen.return());
```

The above sample code prints:
```
// Node v6.3.0
{ done: false, value: 1 }
undefined

// Chrome 51.0.2704.106
{ done: false, value: 1 }
{ done: false, value: undefined }
```

**Comment by johannestroeger** [comment]
has this already been reported at https://bugs.chromium.org/p/v8/issues/list ?

**Comment by jrvidal** [comment]
I imagine that it is already solved for good, since Node 6.3.0 has V8 version 5.0.71.52, while the Chrome version above uses V8 5.1.281.65. [Here](https://github.com/nodejs/node/issues/7904) is some discussion about future V8 versions in Node.

**Comment by yelouafi** [comment]
I think we can get around this by implementing `return` in iterators returned saga helpers. Already pushed a fix  with this solution. I did the tests locally on the @smashercosmo fork and the error is gone (although there are still an error related to `import` statements but that's related to missing node presets)

**Comment by johannestroeger** [comment]
could i help here somehow? we would really like to use yield*ed sagas :(

**Comment by smashercosmo** [comment]
But that's been fixed, no? @yelouafi issue could be closed, am I right?

**Comment by johannestroeger** [comment]
yes, this has been merged, but not yet released.

**Comment by aaronjensen** [comment]
erg, this is a nasty one. A release would be great, especially since we can't just depend on the github version w/o building the release ourselves.

**Comment by yelouafi** [comment]
FYI https://github.com/yelouafi/redux-saga/releases/tag/v0.11.1
